security:
    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\Usuario:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                target: /login

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/logout, roles: [ROLE_VENDEDOR, ROLE_COMPRADOR, ROLE_ADMIN] }
         - { path: ^/index, roles: [ROLE_VENDEDOR, ROLE_COMPRADOR, ROLE_ADMIN] }
         - { path: ^/register/1, roles: [ROLE_ADMIN] }
         - { path: ^/register/2, roles: [ROLE_VENDEDOR, ROLE_ADMIN] }
         - { path: ^/register/3, roles: [ROLE_COMPRADOR, ROLE_ADMIN] } 
         - { path: ^/inmueble, roles: [ROLE_VENDEDOR, ROLE_ADMIN] }
         - { path: ^/cartera, roles: [ROLE_VENDEDOR, ROLE_ADMIN] }
         - { path: ^/propietario, roles: [ROLE_VENDEDOR, ROLE_ADMIN] }
         - { path: ^/status1, roles: [ROLE_VENDEDOR, ROLE_ADMIN] }
         - { path: ^/status2, roles: [ROLE_VENDEDOR, ROLE_ADMIN] }
         - { path: ^/tipologia, roles: [ROLE_VENDEDOR, ROLE_ADMIN] }
         - { path: ^/uso, roles: [ROLE_VENDEDOR, ROLE_ADMIN] }
         - { path: ^/comercializacion, roles: [ROLE_VENDEDOR, ROLE_ADMIN] }
         - { path: ^/tipo/usuario, roles: ROLE_ADMIN }
         - { path: ^/, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
